# Generated by Django 4.0 on 2024-08-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0003_order_is_checked_alter_order_is_agreed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Охроняемые объекты.')),
            ],
            options={
                'verbose_name': 'Охроняемый объект',
                'verbose_name_plural': 'Охроняемые объекты',
                'db_table': 'security_subjects',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
